version: "3"
services:
  app: 
    build: .
    depends_on:
      - db
    ports: 
      - 5500:5500
  db:
    image: postgres
    environment:
      - POSTGRES_USER=spotify
      - POSTGRES_PASSWORD=spotify
      - POSTGRES_DB=spotify
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql